# -*- coding: utf-8 -*-
"""IPO_Clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5g87Daze0je-5Zefb9jCO6Mxwyb_GrU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

df=pd.read_csv("/content/Initial Public Offering.csv")
df.head(5)

df.info()

df.shape

cols = [
'Issue_Size(crores)',
'Offer Price',
'List Price',
'Listing Gain',
'CMP(BSE)',
'CMP(NSE)',
'Current Gains'
]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# # # Data Interpretation
# 1. Date – Date on which the IPO was launched/listed.
# 2. IPO_Name – Name of the company issuing the IPO.
# 3. Issue_Size(crores) – Total amount of money raised through the IPO.
# 4. QIB – Subscription demand from institutional investors.
# 5. HNI – Subscription demand from high-net-worth investors.
# 6. RII – Subscription demand from retail investors.
# 7. Total – Overall IPO subscription across all investor categories.
# 8. Offer Price – Price at which shares were offered in the IPO.
# 9. List Price – Price at which shares started trading on the stock exchange.
# 10. Listing Gain – Percentage profit or loss on the listing day compared to the offer price.
# 11. CMP(BSE) – Current market price of the stock on BSE.
# 12. CMP(NSE) – Current market price of the stock on NSE.
# 13. Current Gains – Percentage return from the IPO offer price to the current market price.

df.duplicated().sum()

df.isnull().sum()

(df.isnull().sum()/len(df)*100).round(2)

df.dropna(inplace=True)

df.isnull().sum()

df['Year'] = pd.DatetimeIndex(df['Date']).year
df['Year'] = df.Date.dt.year

print(df['Date'].head())
print(type(df['Date']))

df.describe( )

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

print(df['Date'].dtype)

df['Month'] = df['Date'].dt.month
df['Quarter'] = df['Date'].dt.quarter

df.columns

df['Positive_Listing'] = (df['Listing Gain'] > 0).astype(int)

df['Size_Category'] = pd.cut(df['Issue_Size(crores)'],
bins=[0,100,500,1000,5000,100000],
labels=['Micro','Small','Medium','Large','Mega'])

df['Sub_Category'] = pd.cut(df['Total'],bins=[0,5,20,50,100,500],
labels=['Low','Moderate','High','Very High','Extreme'])

df.columns

df.to_csv('ipo_clean.csv',index=False)







































































































