# -*- coding: utf-8 -*-
"""IPO_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnQ8xE1SbpPvVCEClM0Fb-nEWmG-UsCH
"""

# ============================================================
#  INDIA IPO PERFORMANCE ANALYSIS & LISTING DAY PREDICTOR
#  Author  : Saikiran Ganga Deenadayalu
#  Dataset : 637 Indian IPOs | 2010 – 2026
#  Tools   : Python · Power BI · Scikit-learn
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

df=pd.read_csv("/content/ipo_clean.csv")
df.sample(5)

print(df['Listing Gain'].describe())
print("Skewness:", df['Listing Gain'].skew())

"""**Chart 1: IPO Volume by Year**

Business Question: Which years saw the highest IPO activity?
"""

plt.figure(figsize=(8, 6))
x1 = sns.countplot(data=df, x='Year', color='lightgray')

heights = [bar.get_height() for bar in x1.patches]

max_height = max(heights)
for bar in x1.patches:
    if bar.get_height() == max_height:
        bar.set_color('orange')
    else:
        bar.set_color('skyblue')

x1.bar_label(x1.containers[0])
plt.xticks(rotation=45)
plt.title("IPO Volume by Year", fontsize=14)
plt.xlabel("Year", fontsize=12)
plt.ylabel("Number of IPOs", fontsize=12)

plt.show()

# Chart 1: IPO Volume by Year
# Business Question:
# Which years saw the highest IPO activity?
plt.figure(figsize=(8, 6))
x1 = sns.countplot(data = df, x = 'Year', color='orange')
x1.bar_label(x1.containers[0])
plt.xticks(rotation=45)
plt.title("IPO Volume by Year", fontsize=14)
plt.xlabel("Year", fontsize=12)
plt.ylabel("Number of IPOs", fontsize=12)
plt.show()

"""**Chart 2: Listing Gain Distribution**

Business Question : How are IPO returns distributed?
"""

sns.histplot(df['Listing Gain'], kde=True,alpha=0.2)
win_pct = df['Positive_Listing'].mean() * 100
plt.title(f'{win_pct:.0f}% of 637 IPOs gave Positive Listing Day Returns')
plt.xlabel('Listing Day Gain (%)')
plt.ylabel('Number of IPOs')
plt.legend()
plt.tight_layout()
plt.show()

fig, x2 = plt.subplots(figsize=(10, 6))
sns.histplot(df['Listing Gain'], bins=55, kde=True,color='blue', alpha=0.65)

mean_gain   = df['Listing Gain'].mean()
median_gain = df['Listing Gain'].median()
win_pct     = df['Positive_Listing'].mean() * 100

x2.axvline(0,           color='red',   linewidth=2,   linestyle='--', label='Break-even (0%)')
x2.axvline(mean_gain,   color='orange', linewidth=2,   linestyle='-',  label=f'Mean: {mean_gain:.1f}%')
x2.axvline(median_gain, color='green', linewidth=2,   linestyle='-.',  label=f'Median: {median_gain:.1f}%')

x2.fill_betweenx([0, x2.get_ylim()[1]], df['Listing Gain'].min(), 0, alpha=0.16, color='red')
x2.fill_betweenx([0, x2.get_ylim()[1]], 0, df['Listing Gain'].max(), alpha=0.16, color='green')

plt.title(f'{win_pct:.0f}% of 637 IPOs gave Positive Listing Day Returns')
plt.xlabel('Listing Day Gain (%)')
plt.ylabel('Number of IPOs')
x2.legend()
plt.tight_layout()
plt.show()

"""**Chart 3: Subscription Category Analysis**

Business Question : Does oversubscription matter?
"""

df['Positive_Listing'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

sub_order = ['Low', 'Moderate', 'High', 'Very High', 'Extreme']
sub_stats = df.groupby('Sub_Category')['Positive_Listing'].agg(win_rate='mean', count='count').reindex(sub_order).reset_index()
sub_avg = df.groupby('Sub_Category')['Listing Gain'].mean().reindex(sub_order).values

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Left: Win Rate
bar_colors = ['red' if w < 0.5 else 'orange' if w < 0.75 else 'green' for w in sub_stats['win_rate']]
bars = ax1.bar(sub_stats['Sub_Category'], sub_stats['win_rate'] * 100, color=bar_colors, width=0.6, edgecolor='white', linewidth=1.2)

ax1.axhline(50, color='black', linestyle='--', linewidth=0.8, label='50% (coin flip)')
ax1.set_ylim(0, 115)
ax1.set_title('Win Rate by Subscription Level\n(Extreme = 100% Win Rate!)')
ax1.set_ylabel('% IPOs with Positive Listing')
ax1.set_xlabel('Subscription Category')

# Right: Avg Listing Gain
bar_colors2 = ['red' if v < 0 else 'blue' for v in sub_avg]
bars2 = ax2.bar(sub_stats['Sub_Category'], sub_avg, color=bar_colors2, width=0.6, edgecolor='white', linewidth=1.2)
ax2.axhline(0, color='black', linewidth=0.8) # ax2.set_ylim(-1.0, 75)
ax2.set_title('Avg Listing Gain by Subscription Level\n(Extreme: +64.9% vs Low: -0.7%)')
ax2.set_ylabel('Avg Listing Gain (%)')
ax2.set_xlabel('Subscription Category')

plt.suptitle(
    'KEY FINDING: Subscription Level is the Strongest Predictor of IPO Success',
    fontsize=13, fontweight='bold', y=1.02)

plt.tight_layout()
ax1.legend()
plt.show()

"""**Chart 4: Subscription vs Listing Gain**

Business Question: Is there a relationship between demand and returns?
"""

fig, ax = plt.subplots(figsize=(13, 6))

colors_scatter = ['green' if p == 1 else 'red' for p in df['Positive_Listing']]
sc = ax.scatter(df['Total'], df['Listing Gain'], c=colors_scatter, alpha=0.45, s=50, edgecolors='white', linewidth=0.3)

ax.axhline(0, color='black', linewidth=1, linestyle='--', alpha=0.5)
ax.axvline(50, color='orange', linewidth=1.5, linestyle='--', alpha=0.7, label='50x subscription threshold')

green_patch = mpatches.Patch(color='green', label='Positive listing')
red_patch   = mpatches.Patch(color='red',   label='Negative listing')
ax.legend(handles=[green_patch, red_patch, ax.get_lines()[0]])

ax.set_xlim(-5, df['Total'].quantile(0.98))
ax.set_xlabel('Total Subscription (x times oversubscribed)')
ax.set_ylabel('Listing Day Gain (%)')
corr = df['Total'].corr(df['Listing Gain'])

ax.set_title('Subscription Rate vs Listing Gain\n' f'Above 50x subscription: nearly all IPOs list positively (Correlation: {corr:.2f})')
plt.tight_layout()
plt.show()

"""**CHART 5 – Monthly Success Heatmap WOW CHART**

 Business Q: Which months are historically luckiest?
"""

pivot = df.pivot_table(values='Positive_Listing',index='Year',columns='Month',aggfunc='mean')
month_map = {1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'May',6:'Jun',
             7:'Jul',8:'Aug',9:'Sep',10:'Oct',11:'Nov',12:'Dec'}
pivot.columns = [month_map[c] for c in pivot.columns]

fig, ax = plt.subplots(figsize=(16, 9))
sns.heatmap(pivot, annot=True, fmt='.0%', cmap='RdYlGn', linewidths=0.4, linecolor='white',
    cbar_kws={'label': '% IPOs with Positive Return', 'shrink': 0.8},vmin=0, vmax=1, ax=ax)

ax.set_title('IPO Success Rate by Month × Year  (2010–2025)\n' 'July is the Best Month to List (86.3% win rate) | March is the Worst (54.5%)',pad=15)
plt.xlabel('Listing Month')
plt.ylabel('Year')
plt.yticks(rotation=90)
plt.tight_layout()
plt.show()

"""**Chart 6: Top 10 IPO Winners**

Business Question: Which IPOs generated the highest listing gains?
"""

colors = ['lightgreen'] + ['skyblue'] * 9
colors2 = ['red'] + ['orange'] * 9
top10 = df.nlargest(10,'Listing Gain')
but10=df.nsmallest(10,'Listing Gain')

plt.figure(figsize=(16, 7))
ax1 = sns.barplot(data= top10, x='Listing Gain', y='IPO_Name', palette=colors)
ax2 = sns.barplot(data= but10, x='Listing Gain', y='IPO_Name', palette=colors2)
for container in ax1.containers:
    ax1.bar_label(container, fmt='%.1f%%', padding=3)
for container in ax2.containers:
    ax2.bar_label(container, fmt='%.1f%%', padding=3)
    plt.suptitle('Sigachi Industries: +252.8% Best Ever | Om Freight: -38.9% Worst Ever',
             fontsize=12, y=1.01)
plt.title('Top 10 & Buttom 10 IPOs by Listing Gain', fontsize=20, fontweight='bold')
plt.xlabel('Listing Gain (%)')
plt.ylabel('IPO Company')
plt.grid(axis='x', linestyle='--', alpha=0.3,color='black')
plt.tight_layout()
plt.show()

"""**Chart 7: Win Rate by QIB Subscription Quartile**

Business Question:  Does higher institutional (QIB) subscription increase the probability of positive IPO listing gains?
"""

df['QIB_Quartile'] = pd.qcut(df['QIB'], 4,labels=['Q1', 'Q2', 'Q3', 'Q4'])

qib_stats = (df.groupby('QIB_Quartile')['Positive_Listing'].mean().reset_index())

plt.figure(figsize=(8, 5))
bar_color=['red','orange','blue','green']
ax = sns.barplot(data= qib_stats, x='QIB_Quartile', y='Positive_Listing',palette=bar_color)

for container in ax.containers:
    ax.bar_label(container, fmt='%.2f%%', padding=3)

plt.title('Win Rate by QIB Subscription Quartile')
plt.xlabel('QIB Quartile')
plt.ylabel('Win Rate (%)')
ax.axhline(y=0.5, color='black', linestyle='--', linewidth=1)
plt.show()

"""**CHART 8 – Quarterly & Monthly Pattern**

 Business Q: When in the year should you apply for IPOs?
"""

size_order  = ['Micro', 'Small', 'Medium', 'Large', 'Mega']
size_stats  = df.groupby('Size_Category').agg( win_rate =('Positive_Listing', 'mean'), avg_gain =('Listing Gain', 'mean'),
                                              count=('IPO_Name', 'count')).reindex(size_order).reset_index()

fig, ax = plt.subplots(figsize=(12, 6))
x = np.arange(len(size_order))

w = 0.38
b1 = ax.bar(x - w/2, size_stats['win_rate'] * 100, w, color='skyblue', label='Win Rate (%)', edgecolor='white')
b2 = ax.bar(x + w/2, size_stats['avg_gain'], w, color='lightgreen', label='Avg Listing Gain (%)', edgecolor='white')

ax.bar_label(b1, fmt='%.0f%%', padding=3, fontsize=9.5)
ax.bar_label(b2, fmt='%.1f%%', padding=3, fontsize=9.5)
ax.axhline(50, color='gray', linestyle='--', linewidth=0.8)
ax.set_xticks(x); ax.set_xticklabels(size_order)
ax.set_xlabel('IPO Size Category')
ax.set_ylabel('Percentage (%)')
ax.legend()
ax.set_title('IPO Performance by Size Category\nAll categories cluster around 68-70% win rate')
plt.tight_layout()
plt.show()

"""**Chart 8: Correlation Heatmap**

Business Question:Which factors influence listing gains?
"""

cols = ['Listing Gain', 'Total', 'QIB', 'HNI', 'RII', 'Current Gains']

corr_matrix = df[cols].corr()

plt.figure(figsize=(10, 7))

sns.heatmap( corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5, linecolor='white', square=True,
            cbar_kws={'label': 'Correlation'},annot_kws={'size': 11, 'weight': 'bold'})

plt.title('Correlation Matrix of IPO Subscription Metrics', fontsize=16, fontweight='bold', pad=15)

plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Chart 9: QIB vs HNI vs RII**

Business Question: Which investor category matters most?
"""

avg_sub = df[['QIB', 'HNI', 'RII']].mean().reset_index()
avg_sub.columns = ['Investor_Type', 'Avg_Subscription']

plt.figure(figsize=(8, 5))
colors = ['gold', 'steelblue', 'tomato']
ax = sns.barplot(data=avg_sub, x='Investor_Type', y='Avg_Subscription', palette=colors)

for container in ax.containers:
    ax.bar_label(container, fmt='%.1f%%', padding=3,fontweight='bold')

plt.title('Average Subscription by Investor Category', fontsize=14, fontweight='bold')

plt.xlabel('Investor Category')
plt.ylabel('Average Subscription (x Times)')
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

# Hidden Gems
hidden_gems = df[
    (df['Total'] < df['Total'].median()) &
    (df['Current Gains'] > 100)
]

hidden_gems[['IPO_Name','Total','Current Gains']]

print("=== TEST 1: Normality ===")
stat, p = stats.shapiro(df['Listing Gain'].sample(50, random_state=42))
print(f"Shapiro W={stat:.4f}, p={p:.6f}")
print(f"Skewness: {df['Listing Gain'].skew():.3f}, Kurtosis: {df['Listing Gain'].kurt():.3f}")

print("\n=== TEST 2: T-test Extreme vs Low ===")
extreme = df[df['Sub_Category']=='Extreme']['Listing Gain']
low = df[df['Sub_Category']=='Low']['Listing Gain']
t, p = stats.ttest_ind(extreme, low)
print(f"t={t:.3f}, p={p:.10f}")
print(f"Extreme mean={extreme.mean():.2f}, Low mean={low.mean():.2f}, diff={extreme.mean()-low.mean():.2f}")

print("\n=== TEST 3: ANOVA across Sub Categories ===")
groups = [df[df['Sub_Category']==c]['Listing Gain'].dropna() for c in ['Low','Moderate','High','Very High','Extreme']]
f, p4 = stats.f_oneway(*groups)
print(f"F={f:.3f}, p={p4:.10f}")

print("\n=== TEST 4: Chi-square Sub_Category vs Positive_Listing ===")
ct = pd.crosstab(df['Sub_Category'], df['Positive_Listing'])
chi2, p6, dof, expected = stats.chi2_contingency(ct)
print(f"chi2={chi2:.3f}, p={p6:.10f}, dof={dof}")